import { appendFileSync, readFileSync, writeFileSync } from 'node:fs'

const report = JSON.parse(readFileSync('actions-up-report.json', 'utf8'))
const count = report.summary?.totalUpdates ?? 0

const lines = ['## GitHub Actions update report', '']

if (count === 0) {
  lines.push('All GitHub Actions are up to date.')
} else {
  lines.push(`Found **${count}** outdated action${count === 1 ? '' : 's'}.`, '')
  lines.push('| Action | File | Current | Latest |')
  lines.push('| --- | --- | --- | --- |')
  for (const update of report.updates ?? []) {
    const name = update.action?.name ?? 'unknown'
    const file = update.action?.file ?? 'unknown'
    const current = update.currentVersion ?? 'unknown'
    const latest = update.latestVersion ?? 'unknown'
    lines.push(`| \`${name}\` | \`${file}\` | \`${current}\` | \`${latest}\` |`)
  }
}

lines.push('', '_Generated by [actions-up](https://github.com/azat-io/actions-up)._')

writeFileSync('actions-up-report.md', lines.join('\n') + '\n')

if (process.env.GITHUB_OUTPUT) {
  appendFileSync(
    process.env.GITHUB_OUTPUT,
    `has-updates=${count > 0}\nupdate-count=${count}\n`,
  )
}

if (process.env.GITHUB_STEP_SUMMARY) {
  appendFileSync(
    process.env.GITHUB_STEP_SUMMARY,
    readFileSync('actions-up-report.md', 'utf8'),
  )
}
